### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by faiface** [hajimehoshi/go-mp3#11]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x49408a]

goroutine 1 [running]:
github.com/hajimehoshi/go-mp3.(*source).readNextFrame(0xc4200780c0, 0x0, 0xc42008e018, 0x7fa7adbcd028, 0xc42008e018, 0x1)
        /home/faiface/go/src/github.com/hajimehoshi/go-mp3/read.go:42 +0x6a
github.com/hajimehoshi/go-mp3.NewDecoder(0x728be0, 0xc42008e018, 0xc42008e018, 0x0, 0x0)
        /home/faiface/go/src/github.com/hajimehoshi/go-mp3/decode.go:291 +0x119
```

This happens when I attempt to play any song converted to MP3 using VLC and a few other files.

**Comment by hajimehoshi** [comment]
Could you give an example to reproduce this?

**Comment by faiface** [comment]
Just play the go-mp3 example with any MP3 produced from VLC.

**Comment by hajimehoshi** [comment]
Confirmed.

**Comment by hajimehoshi** [comment]
Fixed
