### ISSUE TITLE
Crashes with some MP3's

### ISSUE THREAD

**Issue by faiface** [hajimehoshi/go-mp3#30]
Decoding crashes with the MP3 from here and other MP3's from that site: http://soundbible.com/2122-40-Smith-Wesson.html

```
signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a9fa7]

goroutine 1 [running]:
github.com/hajimehoshi/go-mp3.(*source).readNextFrame(0xc420098180, 0x0, 0xc4200a2018, 0x7f5e2f9c0f70, 0xc4200a2018, 0x1)
        /home/faiface/go/src/github.com/hajimehoshi/go-mp3/read.go:42 +0x67
github.com/hajimehoshi/go-mp3.NewDecoder(0x506580, 0xc4200a2018, 0xc420063ea8, 0xc4200a2018, 0x0)
        /home/faiface/go/src/github.com/hajimehoshi/go-mp3/decode.go:291 +0x133
github.com/faiface/beep/mp3.Decode(0x506580, 0xc4200a2018, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/faiface/go/src/github.com/faiface/beep/mp3/decode.go:30 +0x7e
```

**Comment by hajimehoshi** [comment]
I couldn't reproduce this. The sounds was played correctly.

**Comment by faiface** [comment]
Interesting, now I updated and it works. Probably just an older bug.
