### ISSUE TITLE
panic in internal/maindata.readHuffman

### ISSUE THREAD

**Issue by djadala** [hajimehoshi/go-mp3#51]
Hi,
i write simple program to read all mp3 files, just to check that they are not corrupted, but get panic after some errors
(note  readHuffman failed)
i work in gopath mode (use latest source)

```
2022/11/01 09:14:06 mp3: free bitrate format is not supported. Header word is 0xffe607df at position 344519
2022/11/01 09:14:11 mp3: only layer3 (want 1; got 3) is supported
2022/11/01 09:14:16 mp3: only layer3 (want 1; got 3) is supported
2022/11/01 09:14:17 mp3: only layer3 (want 1; got 3) is supported
2022/11/01 09:14:26 mp3: free bitrate format is not supported. Header word is 0xffff0000 at position 3310324
2022/11/01 09:14:30 mp3: free bitrate format is not supported. Header word is 0xffff0400 at position 3680769
2022/11/01 09:14:39 mp3: only layer3 (want 1; got 3) is supported
2022/11/01 09:14:43 mp3: only layer3 (want 1; got 3) is supported
2022/11/01 09:14:59 mp3: only layer3 (want 1; got 3) is supported
2022/11/01 09:15:13 mp3: only layer3 (want 1; got 3) is supported
2022/11/01 09:15:29 mp3: readHuffman failed: invalid index j: 24
2022/11/01 09:15:43 mp3: only layer3 (want 1; got 3) is supported
2022/11/01 09:15:53 mp3: free bitrate format is not supported. Header word is 0xffff00b5 at position 3409454
2022/11/01 09:15:54
panic: runtime error: index out of range [-4]

goroutine 6 [running]:
github.com/hajimehoshi/go-mp3/internal/maindata.readHuffman(0xc0000142d0, 0x2?, 0xc0001322c0, 0xc0000f3000, 0xc0001cc000?, 0xc000132f38?, 0x1)
	/home/jambo/golang/src/github.com/hajimehoshi/go-mp3/internal/maindata/huffman.go:124 +0x5cf
github.com/hajimehoshi/go-mp3/internal/maindata.getScaleFactorsMpeg2(0xc0000142d0, 0xfff38250, 0xc0001322c0)
	/home/jambo/golang/src/github.com/hajimehoshi/go-mp3/internal/maindata/maindata.go:172 +0x1e6
github.com/hajimehoshi/go-mp3/internal/maindata.Read({0x7fb59b2e60f8, 0xc0001cc000}, 0xfff38250?, 0xfff38250, 0xc0001322c0)
	/home/jambo/golang/src/github.com/hajimehoshi/go-mp3/internal/maindata/maindata.go:111 +0x117
github.com/hajimehoshi/go-mp3/internal/frame.Read({0x4e9588?, 0xc0001cc000}, 0x0?, 0xc000446000)
	/home/jambo/golang/src/github.com/hajimehoshi/go-mp3/internal/frame/frame.go:97 +0x155
github.com/hajimehoshi/go-mp3.(*Decoder).readFrame(0xc0004a5200)
	/home/jambo/golang/src/github.com/hajimehoshi/go-mp3/decode.go:42 +0x34
github.com/hajimehoshi/go-mp3.(*Decoder).Read(0xc0004a5200, {0xc0004c8e98, 0x1000, 0x1000?})
	/home/jambo/golang/src/github.com/hajimehoshi/go-mp3/decode.go:60 +0x4a
main.decode({0xc0000208c0?, 0x39?})
	/home/jambo/go/src/jambo/cmd/mediacheck/check.go:30 +0x205
main.Decode({0xc0000208c0, 0x39})
	/home/jambo/go/src/jambo/cmd/mediacheck/check.go:43 +0x5f
main.do(0x0?, 0x0?)
	/home/jambo/go/src/jambo/cmd/mediacheck/check.go:52 +0x71
created by main.main
	/home/jambo/go/src/jambo/cmd/mediacheck/check.go:118 +0xb7

```

```go
package main

import (
	"flag"
	"fmt"
	"io"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"sync"

	"github.com/hajimehoshi/go-mp3"
)

func decode(p string) error {
	f, err := os.Open(p)
	if err != nil {
		log.Println(err)
		return err
	}
	defer f.Close()
	d, err := mp3.NewDecoder(f)
	if err != nil {
		log.Println(err)
		return err
	}
	for {
		var buf [4096]byte
		_, err := d.Read(buf[:])
		if err != nil {
			if err != io.EOF {
				log.Println(err)
				return err
			}
			return nil
		}
	}
}

func Decode(p string) {
	log.Println(p)
	err := decode(p)
	if err != nil {
		log.Println(p, err)
	}
}

func do(f chan string, wg *sync.WaitGroup) {
	defer wg.Done()
	for p := range f {
		Decode(p)
	}
}

var walkfiles chan string

func visitDir(path string, d fs.DirEntry, err error) error {

	if err != nil {
		log.Println(path, err)
		return err
	}

	if d.Type().IsRegular() {
		ext := filepath.Ext(path)
		if ext != ".mp3" {
			fmt.Println(path)
			// if ext == ".MP3" {
			// 	os.Rename(path, path[:len(path)-3]+"mp3")
			// 	fmt.Println(path[:len(path)-3] + "mp3")
			// }

		} else {
			// fmt.Println(path)
			// decode(path)
			walkfiles <- path
		}
	}
	return nil
}

func main() {
	const N = 12
	var wg sync.WaitGroup

	flag.Parse()
	walkfiles = make(chan string, N*2)
	for i := 0; i < N; i++ {
		wg.Add(1)
		go do(walkfiles, &wg)
	}

	for _, root := range flag.Args() {

		// err := filepath.Walk(root, visit)
		err := filepath.WalkDir(root, visitDir)
		if err != nil {
			log.Println(root, err)
		}
	}
	close(walkfiles)
	wg.Wait()
}
```

**Comment by hajimehoshi** [comment]
Is the mp3 file available? Thanks,

**Comment by djadala** [comment]
this does not reproduce on single file, only when when dirs are walked on filesystem.
now i try to find minimal set of files to reproduce.
I will inform you when find such set ...

**Comment by djadala** [comment]
this also reproduce with -race, no race reported

**Comment by djadala** [comment]
panic is caused by single file (playable)
see attached file, encrypted with ```gpg -c 1.mp3```, decrypt with ```gpg -d 1.mp3.gpg```, password is sent to your email
[bad.zip](https://github.com/hajimehoshi/go-mp3/files/9908960/bad.zip)

**Comment by hajimehoshi** [comment]
Though this mp3 file sounded weired, I couldn't see the crash. Do I have to play through the entire file?

**Comment by hajimehoshi** [comment]
Finally I couldn't see the crash after playing through the file. What I did is just replace classic.mp3 with your 1.mp3 in the Oto's example.

**Comment by djadala** [comment]
can you try my example program from 1st comment ?

**Comment by hajimehoshi** [comment]
I'll try later.

**Comment by djadala** [comment]
or with this:
```go
func decode(p string) error {
	f, err := os.Open(p)
	if err != nil {
		// log.Println(err)
		return err
	}
	defer f.Close()
	d, err := mp3.NewDecoder(f)
	if err != nil {
		// log.Println(err)
		return err
	}
	for {
		var buf [4096]byte
		_, err := d.Read(buf[:])
		if err != nil {
			if err != io.EOF {
				// log.Println(err)
				return err
			}
			return nil
		}
	}
}

func main() {
	flag.Parse()

	for _, file := range flag.Args() {
		decode(file)
	}
}

```

```
mediacheck 1.mp3
panic: runtime error: index out of range [-4]

goroutine 1 [running]:
github.com/hajimehoshi/go-mp3/internal/maindata.readHuffman(0xc0004aae10, 0x2?, 0xc0003a4840, 0xc0003b5000, 0xc0000a8150?, 0xc0003a4438?, 0x1)
	/home/jambo/golang/src/github.com/hajimehoshi/go-mp3/internal/maindata/huffman.go:124 +0x5cf
github.com/hajimehoshi/go-mp3/internal/maindata.getScaleFactorsMpeg2(0xc0004aae10, 0xfff38250, 0xc0003a4840)
	/home/jambo/golang/src/github.com/hajimehoshi/go-mp3/internal/maindata/maindata.go:172 +0x1e6
github.com/hajimehoshi/go-mp3/internal/maindata.Read({0x7f2fbcf547e8, 0xc0000a8150}, 0xfff38250?, 0xfff38250, 0xc0003a4840)
	/home/jambo/golang/src/github.com/hajimehoshi/go-mp3/internal/maindata/maindata.go:111 +0x117
github.com/hajimehoshi/go-mp3/internal/frame.Read({0x4d4a68?, 0xc0000a8150}, 0x0?, 0xc0003a9500)
	/home/jambo/golang/src/github.com/hajimehoshi/go-mp3/internal/frame/frame.go:97 +0x155
github.com/hajimehoshi/go-mp3.(*Decoder).readFrame(0xc0000b61e0)
	/home/jambo/golang/src/github.com/hajimehoshi/go-mp3/decode.go:42 +0x34
github.com/hajimehoshi/go-mp3.(*Decoder).Read(0xc0000b61e0, {0xc0000feef0, 0x1000, 0x259?})
	/home/jambo/golang/src/github.com/hajimehoshi/go-mp3/decode.go:60 +0x4a
main.decode({0x7fff2918ffba?, 0xc0000ba010?})
	/home/jambo/go/src/jambo/cmd/mediacheck/check.go:31 +0x15e
main.main()
	/home/jambo/go/src/jambo/cmd/mediacheck/check.go:46 +0xac

```

**Comment by hajimehoshi** [comment]
Confirmed.

**Comment by hajimehoshi** [comment]
I'm not confident about my fix to be honest, but could you try 26f0b17459ab4b2b3d9d2b484a27a4eab3cca17b ? Thanks,

**Comment by djadala** [comment]
Yes,   26f0b17459ab4b2b3d9d2b484a27a4eab3cca17b fixes this panic.

**Comment by hajimehoshi** [comment]
Thank you for confirming!
